GET {{APIURL}}/categorias/getAll


### get by id
GET {{APIURL}}/categorias/getById/100

### create category
POST {{APIURL}}/categorias/create
Content-Type: application/json

{
    "name" : ""
}

### delete category
DELETE {{APIURL}}/categorias/delete/7